name: tyba_front_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # Firebase
  firebase_analytics: ^5.0.6
  firebase_core: ^0.4.2+1
  firebase_crashlytics: ^0.1.1+2
  cloud_firestore: ^0.12.10+2
  firebase_auth: ^0.15.0+1

  # Vendors
  flare_flutter: ^1.7.3
  get_it: ^3.0.3
  meta: ^1.1.7
  provider: ^3.2.0
  toast: ^0.1.5
  localstorage: ^3.0.1+4
  flutter_google_places: ^0.2.3
  google_maps_flutter: ^0.5.21+12
  google_sign_in: 4.0.0
  location: ^2.3.5
  permission_handler: ^4.0.0
  http: ^0.12.0+2
  flutter_rating_bar: ^3.0.0
  url_launcher: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans/Regular.ttf
  assets:
   - assets/images/
   - assets/anims/foods.flr
   - assets/anims/loading_food.flr
   - assets/anims/maps.flr
   - assets/anims/search_location.flr